### ISSUE TITLE
chaduke - getUserPairShare() has a divide-before-multiply precision loss issue

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-olympus-judging#19]
chaduke

medium

# getUserPairShare() has a divide-before-multiply precision loss issue

## Summary
``getUserPairShare()`` has a divide-before-multiply precision loss issue.

## Vulnerability Detail

``getUserPairShare()`` returns a user's pair share: 

[https://github.com/sherlock-audit/2023-03-olympus/blob/main/sherlock-olympus/src/policies/BoostedLiquidity/BLVaultLido.sol#L281-L301](https://github.com/sherlock-audit/2023-03-olympus/blob/main/sherlock-olympus/src/policies/BoostedLiquidity/BLVaultLido.sol#L281-L301)

However, we have a divide-before-multiply issue here:

```javascript
 uint256 userOhmShare = (userLpBalance * balances[0]) / liquidityPool().totalSupply();
        uint256 expectedWstethShare = (userOhmShare * wstethOhmPrice) / _OHM_DECIMALS;
```
First,  there is a division in the first line above, and then in the second line, we have a multiplication by ``wstethOhmPrice``. As a result, we might lose a precision up to the ``liquidityPool().totalSupply()`` here.

## Impact
A divide-before-multiply might lead to precision loss up to liquidityPool().totalSupply().

## Code Snippet
See above

## Tool used
VScode

Manual Review

## Recommendation
Change it to multiply-before-divide as follows:
```diff
    function getUserPairShare() public view override returns (uint256) {
        // If total supply is 0 return 0
        if (liquidityPool().totalSupply() == 0) return 0;

        // Get user's LP balance
        uint256 userLpBalance = getLpBalance();

        // Get pool balances
        (, uint256[] memory balances, ) = vault().getPoolTokens(liquidityPool().getPoolId());

        // Get user's share of the wstETH
        uint256 userWstethShare = (userLpBalance * balances[1]) / liquidityPool().totalSupply();

        // Check pool against oracle price
        // getTknOhmPrice returns the amount of wstETH per 1 OHM based on the oracle price
        uint256 wstethOhmPrice = manager().getTknOhmPrice();
-        uint256 userOhmShare = (userLpBalance * balances[0]) / liquidityPool().totalSupply();
-        uint256 expectedWstethShare = (userOhmShare * wstethOhmPrice) / _OHM_DECIMALS;
+       uint256 expectedWstethShare = (userLpBalance * balances[0]  * wstethOhmPrice) / liquidityPool().totalSupply() / _OHM_DECIMALS;


        return userWstethShare > expectedWstethShare ? expectedWstethShare : userWstethShare;
    }
```

**Comment by 0xLienid** [comment]
Fix Implementation: https://github.com/0xLienid/sherlock-olympus/pull/9/files

**Comment by hrishibhat** [comment]
Given that the `userOhmShare` will still be 18 dp after the division the precision loss is a negligible amount, considering the impact to be low.
