### ISSUE TITLE
chaduke - deposit() fails to decrease allowance for MINTR(), and only increase allowance when unusedOhm > 0.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-olympus-judging#20]
chaduke

medium

# deposit() fails to decrease allowance for MINTR(), and only increase allowance when unusedOhm > 0.

## Summary
``deposit()`` fails to decrease allowance for MINTR(), and only increase allowance when unusedOhm > 0. As a result, the amount of Ohm minted might go beyond limit.

## Vulnerability Detail
``deposit()`` allows a user to transfer `` wstETH`` to the vault and Ohm to the vault. 

[https://github.com/sherlock-audit/2023-03-olympus/blob/main/sherlock-olympus/src/policies/BoostedLiquidity/BLVaultLido.sol#L143-L200](https://github.com/sherlock-audit/2023-03-olympus/blob/main/sherlock-olympus/src/policies/BoostedLiquidity/BLVaultLido.sol#L143-L200)

However, at the following line: L168
```javascript
            manager.mintOhmToVault(ohmMintAmount);
```
the function fails to decrease the allowance for MINTER() first before minting. 

This is in contrast to the case for withdraw(), which will increase allowance for MINTER() first, and then burn ohm from vault.

```javascript
// Burn OHM
        ohm.increaseAllowance(MINTR(), ohmAmountOut);
        manager.burnOhmFromVault(ohmAmountOut);

```

On the other hand, the ``deposit()`` function even increases the allowance of MINTER() when ``unusedOhm > 0``. 

```javascript
 if (unusedOhm > 0) {
            ohm.increaseAllowance(MINTR(), unusedOhm);
            manager.burnOhmFromVault(unusedOhm);
        }
```

## Impact
In summary, the ``deposit()`` function will never decrease, and in some cases, only increase the allowance for MINTER() after minting ohm. As a result, the allowance for MINTER() is not correctly modified. The minting limit will not properly set for MINTER().

## Code Snippet
See above

## Tool used
VSCode

Manual Review

## Recommendation
We need to decrease the allowance for MINTER when we mint ohm:
```diff
function deposit(
        uint256 amount_,
        uint256 minLpAmount_
    ) external override onlyWhileActive onlyOwner nonReentrant returns (uint256 lpAmountOut) {
        // Cache variables into memory
        IBLVaultManagerLido manager = manager();
        OlympusERC20Token ohm = ohm();
        ERC20 wsteth = wsteth();
        IBasePool liquidityPool = liquidityPool();
        IAuraBooster auraBooster = auraBooster();

        // Calculate OHM amount to mint
        // getOhmTknPrice returns the amount of OHM per 1 wstETH
        uint256 ohmWstethPrice = manager.getOhmTknPrice();
        uint256 ohmMintAmount = (amount_ * ohmWstethPrice) / _WSTETH_DECIMALS;

        // Block scope to avoid stack too deep
        {
            // Cache OHM-wstETH BPT before
            uint256 bptBefore = liquidityPool.balanceOf(address(this));

            // Transfer in wstETH
            wsteth.safeTransferFrom(msg.sender, address(this), amount_);

            // Mint OHM
+         ohm.decreaseAllowance(MINTR(), ohmMintAmount);
            manager.mintOhmToVault(ohmMintAmount);

            // Join Balancer pool
            _joinBalancerPool(ohmMintAmount, amount_, minLpAmount_);

            // OHM-PAIR BPT after
            lpAmountOut = liquidityPool.balanceOf(address(this)) - bptBefore;
            manager.increaseTotalLp(lpAmountOut);

            // Stake into Aura
            liquidityPool.approve(address(auraBooster), lpAmountOut);
            bool depositSuccess = auraBooster.deposit(pid(), lpAmountOut, true);
            if (!depositSuccess) revert BLVaultLido_AuraDepositFailed();
        }

        // Return unused tokens
        uint256 unusedOhm = ohm.balanceOf(address(this));
        uint256 unusedWsteth = wsteth.balanceOf(address(this));

        if (unusedOhm > 0) {
            ohm.increaseAllowance(MINTR(), unusedOhm);
            manager.burnOhmFromVault(unusedOhm);
        }

        if (unusedWsteth > 0) {
            wsteth.safeTransfer(msg.sender, unusedWsteth);
        }

        // Emit event
        emit Deposit(ohmMintAmount - unusedOhm, amount_ - unusedWsteth);

        return lpAmountOut;
    }
```

**Comment by 0xLienid** [comment]
Approval of the MINTR to spend the contract's OHM is only needed on burning. So you approve the amount to burn.
