### ISSUE TITLE
Bauer - AuraPool.withdrawAndUnwrap boolean return value not handled in BLVaultLido.sol

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-olympus-judging#34]
Bauer

medium

# AuraPool.withdrawAndUnwrap boolean return value not handled in BLVaultLido.sol

## Summary
`AuraPool.withdrawAndUnwrap()` boolean return value not handled in BLVaultLido.sol

## Vulnerability Detail
The `BLVaultLido.withdraw()` is used to unstake from Aura and  exit Balancer pool. The `withdrawAndUnwrap()` function in the Aura implementation returns a boolean to acknowledge that the unstake is successful.  However, the protocol does not handle the `AuraPool.withdrawAndUnwrap()` boolean return value.
 https://etherscan.io/address/0x7818A1DA7BD1E64c199029E86Ba244a9798eEE10#code#F17#L261
```solidity
    function withdrawAndUnwrap(uint256 amount, bool claim) public returns(bool){
        _withdrawAndUnwrapTo(amount, msg.sender, msg.sender);
        //get rewards too
        if(claim){
            getReward(msg.sender,true);
        }
        return true;
    }
```
```solidity
function withdraw(
        uint256 lpAmount_,
        uint256[] calldata minTokenAmounts_,
        bool claim_
    ) external override onlyWhileActive onlyOwner nonReentrant returns (uint256, uint256) {
        // Cache variables into memory
        OlympusERC20Token ohm = ohm();
        ERC20 wsteth = wsteth();
        IBLVaultManagerLido manager = manager();

        // Cache OHM and wstETH balances before
        uint256 ohmBefore = ohm.balanceOf(address(this));
        uint256 wstethBefore = wsteth.balanceOf(address(this));

        // Decrease total LP
        manager.decreaseTotalLp(lpAmount_);

        // Unstake from Aura
        auraRewardPool().withdrawAndUnwrap(lpAmount_, claim_);

```
## Impact
If the boolean value is not handled, the transaction may fail silently.
## Code Snippet
https://github.com/sherlock-audit/2023-03-olympus/blob/main/sherlock-olympus/src/policies/BoostedLiquidity/BLVaultLido.sol#L221

## Tool used

Manual Review

## Recommendation
Recommend checking for success return value

  ```solidity
         bool withdrawSuccess =   auraRewardPool().withdrawAndUnwrap(lpAmount_, claim_);
        if (!withdrawSuccess  revert BLVaultLido_AuraWithdrawFailed();
```

**Comment by 0xLienid** [comment]
This is really a low issue, but I'll add the success check anyways.

**Comment by 0xLienid** [comment]
Fix Implementation: https://github.com/0xLienid/sherlock-olympus/pull/10/files

**Comment by hrishibhat** [comment]
Agreed, considering this issue as low
