### ISSUE TITLE
Bahurum - Users deposit could get stuck due to check in `decreaseTotalLp` function

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-olympus-judging#43]
Bahurum

medium

# Users deposit could get stuck due to check in `decreaseTotalLp` function

## Summary
In the `decreaseTotalLp` function in `BLVaultManagerLido.sol` the check will revert for the last users withdrawing if other users withdrew aura lp tokens sent directly to their vault.

## Vulnerability Detail
`decreaseTotalLp()` will revert if the amount to be withdrawn is larger than the `totalLp` in the all the vaults. Normally this will not revert and as the last user withdraws all its funds from its vault, then `totalLp` will be set back to 0. 

The problem incurrs when an user sends by error some aura deposit vault tokens to its vault (mistakes of this kind are seen from time to time due to users misunderstandings of how things work). The user will now be able to withdraw more than originally deposited.

Example:
- Alice creates a vault
- Alice sends 10 aura deposit tokens to her vault because she does not understand how to interact with the vault
- Alice does some research and understands how to interact with the vault
- Alice deposits 10 wstETH, `totalLp` is increased to 10.
- Bob creates a vault
- Bob deposits 10 wstETH, `totalLp` is increased to 20.
- Alice withdraws the max amount of lp from her vault, which is 20 because of the initial mistake. `totalLP` is decreased to 0.
- Bob wants to withdraw but his transaction reverts due to the check in `decreaseTotalLp`. Bob's deposit is stuck forever

## Impact
Deposits of last users withdrawing could get stuck.

## Code Snippet
https://github.com/sherlock-audit/2023-03-olympus/blob/main/sherlock-olympus/src/policies/BoostedLiquidity/BLVaultManagerLido.sol#L277-L280

## Tool used

Manual Review

## Recommendation

```solidity
function decreaseTotalLp(uint256 amount_) external override onlyWhileActive onlyVault {
-   if (amount_ > totalLp) revert BLManagerLido_InvalidLpAmount();
+   if (amount_ > totalLp) amount_ = totalLp;
    totalLp -= amount_;
}
```

Duplicate of #4

**Comment by 0xLienid** [comment]
Solution to #004 should mitigate this

**Comment by 0xLienid** [comment]
@IAm0x52 Do you prefer this solution more than what I did for #004?
