### ISSUE TITLE
Bahurum - If wstETH or OHM are added to Aura extra rewards, then they will be lost when withdrawing with claim

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-olympus-judging#44]
Bahurum

medium

# If wstETH or OHM are added to Aura extra rewards, then they will be lost when withdrawing with claim

## Summary
If aura adds wstETH or OHM as extrarewards, then this extra rewards will be lost when withdrawing with claim

## Vulnerability Detail
In `BLVaultLido.withdraw()`, if the rewards are wstETH they will be sent to the treasury by the check on wstETH value returned, and if they are OHM they will be burned in `manager.burnOhmFromVault(ohmAmountOut)`.

Example, let's say wstETH is in extraRewards.
1. OHM price is 200 OHM per wstETH
2. User deposits 10 wstETH
3. After sometime he has accumulated 1 wstETH of rewards
4. User withdraws all with `claim_` = true
   1. ohmBefore = 0, wstethBefore = 0
   2. ohmAmountOut = 2000, wstethAmountOut = 10 + 1 rewards = 11
   3. wstethOhmPrice = 0.005, expectedWstethAmountOut = 2000*0.005 = 10
   4. 1 wstETH from rewards is sent to treasury

If OHM is in the rewards, all rewards in OHM will be burned along with the OHM obtained after removing lp from the balancer pool.

## Impact
Extra rewards in wstETH or OHM will be lost when withdrawing and claiming at the same time.

## Code Snippet
https://github.com/sherlock-audit/2023-03-olympus/blob/main/sherlock-olympus/src/policies/BoostedLiquidity/BLVaultLido.sol#L235-L244
## Tool used

Manual Review

## Recommendation
send rewards just after claiming, instead than at the end of `withdraw()`

```solidity
        // Unstake from Aura
        auraRewardPool().withdrawAndUnwrap(lpAmount_, claim_);
+       // Return rewards to owner
+       if (claim_) _sendRewards();
```

**Comment by 0xLienid** [comment]
this isn't really an issue since we will be in communication with the Aura team
